<?xml version="1.0"?>
<package format="3">
  <name>mp_gesture_pkg</name>
  <version>0.0.1</version>
  <description>Rule-based hand gesture recognizer (MediaPipe Hands) → /intents_raw</description>
  <maintainer email="sayak.deb26@gmail.com">sayak</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <exec_depend>amr_interfaces</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
