<?xml version="1.0"?>
<package format="3">
  <name>frame_simplifier_pkg</name>
  <version>0.0.1</version>
  <description>Lightweight frame simplifier: resizes, converts to bgr8, and republishes at fixed FPS.</description>
  <maintainer email="sayak.deb26@gmail.com">sayak</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
