<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>vlm_videollava_pkg</name>
  <version>0.0.0</version>
  <description>Video-LLaVA VLM Package</description>
  <maintainer email="sayak@example.com">sayak</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>vlm_interfaces</exec_depend>
  <!-- Add python dependencies if we could, but rosdep handles them usually. 
       We assume transformers/torch installed in environment. -->

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
